<link rel="stylesheet" href="../config/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="../config/bower_components/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="../config/bower_components/Ionicons/css/ionicons.min.css">
  <link rel="stylesheet" href="../config/dist/css/AdminLTE.min.css">
  <link rel="stylesheet" href="../config/dist/css/skins/_all-skins.min.css">
  <link rel="stylesheet" href="../config/bower_components/morris.js/morris.css">
  <link rel="stylesheet" href="../config/bower_components/jvectormap/jquery-jvectormap.css">
  <link rel="stylesheet" href="../config/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <link rel="stylesheet" href="../config/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <link rel="stylesheet" href="../config/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
  <link rel="stylesheet" href="../config/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">